import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // 🧹 Clean old data before reseeding
  await prisma.product.deleteMany();

  await prisma.product.createMany({
    data: [   
      {
       id: "1",
       sku: "BOOK-001",
       title: "Bottle Ka Tufan",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/01-Bottle-ka-tufan.jpg",
       active: true,
     },
     {
       id: "2",
       sku: "BOOK-002",
       title: "Haaye Budhapa",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/02-haay-bhudapa.jpg",
       active: true,
     },
     {
       id: "3",
       sku: "BOOK-003",
       title: "Gar Bhai Na Hota",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/03-gar-bhai-na-hota.jpg",
       active: true,
     },
     {
       id: "4",
       sku: "BOOK-004",
       title: "Kanya Daan",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/04-kanya-daan.jpg",
       active: true,
     },
     {
       id: "5",
       sku: "BOOK-005",
       title: "Prem Jivan Ka Mahamantra",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/05-Prem-Jivan-ka-mhamantra.jpg",
       active: true,
     },
     {
       id: "6",
       sku: "BOOK-006",
       title: "Aatmahatya",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/06-aatmhatya.jpg",
       active: true,
     },
     {
       id: "7",
       sku: "BOOK-007",
       title: "Bhookh",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/07-bhookh.jpg",
       active: true,
     },
     {
       id: "8",
       sku: "BOOK-008",
       title: "Zindagi Ka Naam Dosti",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/08-jindgi-ka-naam-dosti.jpg",
       active: true,
     },
     {
       id: "9",
       sku: "BOOK-009",
       title: "Lohe Ki Deewar",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/09-lohe-ki-divar.jpg",
       active: true,
     },
     {
       id: "10",
       sku: "BOOK-010",
       title: "Mithi Vani",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/10-mithi-vani.jpg",
       active: true,
     },
     {
       id: "11",
       sku: "BOOK-011",
       title: "Samasya",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/11-samasya.jpg",
       active: true,
     },
     {
       id: "12",
       sku: "BOOK-012",
       title: "Meri Nazro Me Azadi",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/12-meri-mazro-m-azadi.jpg",
       active: true,
     },
     {
       id: "13",
       sku: "BOOK-013",
       title: "Sant Sadhana",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/13-sant-sadhu.jpg",
       active: true,
     },
     {
       id: "14",
       sku: "BOOK-014",
       title: "Anasakt Yogi",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 3500,
       imageUrl: "/images/Products/Books/14-anasakt-yogi.jpg",
       active: true,
     },
     {
       id: "15",
       sku: "BOOK-015",
       title: "Sanskaro Ka Shankhnaad",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/15-sanskaro-ka-sankhnaad.jpg",
       active: true,
     },
     {
       id: "16",
       sku: "BOOK-016",
       title: "Aur Meri Maa Ro Padhi",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/16-aur-meri-ma-ro-phdi.jpg",
       active: true,
     },
     {
       id: "17",
       sku: "BOOK-017",
       title: "Bharat Ka Bhagya Vidhata",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/17-bharat-ka-bhagya-vidhata.jpg",
       active: true,
     },
     {
       id: "18",
       sku: "BOOK-018",
       title: "Aastha Or Aradhya",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/18-astha-or-aradhya.jpg",
       active: true,
     },
     {
       id: "20",
       sku: "BOOK-020",
       title: "Ek Choti Si Baat Part-1",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 15000,
       imageUrl: "/images/Products/Books/20-ek-choti-si-bath-bhag-ek.jpg",
       active: true,
     },
     {
       id: "21",
       sku: "BOOK-021",
       title: "Ek Choti Si Baat Part-2",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 15000,
       imageUrl: "/images/Products/Books/21-ek-choti-si-bath-bhag-2.jpg",
       active: true,
     },
     {
       id: "22",
       sku: "BOOK-022",
       title: "Mann Ke Vaade Mann Ki Baaten",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 8000,
       imageUrl: "/images/Products/Books/22-maan-ke-vade-man-ki-baaten.jpg",
       active: true,
     },
     {
       id: "23",
       sku: "BOOK-023",
       title: "Bharat Gaurav",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/23-bharat-gaurav.jpg",
       active: true,
     },
     {
       id: "24",
       sku: "BOOK-024",
       title: "Bharat Gaurav Ne Kaha",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/24-bharat-gaurav-ne-kha.jpg",
       active: true,
     },
     {
       id: "26",
       sku: "BOOK-026",
       title: "Ram Bina Jag Suna",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/26-ram-bina-jag-suna.jpg",
       active: true,
     },
     {
       id: "27",
       sku: "BOOK-027",
       title: "Maa Dev Mati",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 5000,
       imageUrl: "/images/Products/Books/27-ma-dev-mati.jpg",
       active: true,
     },
     {
       id: "28",
       sku: "BOOK-028",
       title: "Dhamm Sharnam",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 5000,
       imageUrl: "/images/Products/Books/28-dhaamm-sharnam.jpg",
       active: true,
     },
     {
       id: "29",
       sku: "BOOK-029",
       title: "Oh! This Old Age",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/29-oh-this-old-age.jpg",
       active: true,
     },
     {
       id: "31",
       sku: "BOOK-031",
       title: "Meri Awaaz Suno",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 3500,
       imageUrl: "/images/Products/Books/31-meri-awaj-suno.jpg",
       active: true,
     },
     {
       id: "33",
       sku: "BOOK-033",
       title: "Charch Ki Chokhat Par Prem Ka Pulak",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/33-charch-ki-chokhat-par-prem-ka-pulak.jpg",
       active: true,
     },
     {
       id: "34",
       sku: "BOOK-034",
       title: "Aakhir Kyun?",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 10000,
       imageUrl: "/images/Products/Books/34-aakhir-kyun.jpg",
       active: true,
     },
     {
       id: "35",
       sku: "BOOK-035",
       title: "Pratham Sopan",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 3500,
       imageUrl: "/images/Products/Books/35-prathan-sopan.jpg",
       active: true,
     },
     {
       id: "36",
       sku: "BOOK-036",
       title: "Prabhu Gungaan",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/36-prabhu-gungaan.jpg",
       active: true,
     },
     {
       id: "38",
       sku: "BOOK-038",
       title: "Aacharya Pulak Sindhu Vidhaan",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/38-aachary-pulak-sindhu-vidhan.jpg",
       active: true,
     },
     {
       id: "39",
       sku: "BOOK-039",
       title: "Deepawali Jeen Pujan Vidhi",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 2000,
       imageUrl: "/images/Products/Books/39-dipawli-jin-poojan.jpg",
       active: true,
     },
     {
       id: "40",
       sku: "BOOK-040",
       title: "Suprabhatotsav",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 5000,
       imageUrl: "/images/Products/Books/40-suprabhotsav.jpg",
       active: true,
     },
     {
       id: "41",
       sku: "BOOK-041",
       title: "Guru Bhakti",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 5000,
       imageUrl: "/images/Products/Books/41-Guru-bhakti.jpg",
       active: true,
     },
     {
       id: "42",
       sku: "BOOK-042",
       title: "Aatma Aradhana",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 5000,
       imageUrl: "/images/Products/Books/42-aatm-aradhna.jpg",
       active: true,
     },
     {
       id: "53",
       sku: "BOOK-053",
       title: "Sarvasva Part-1",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 15000,
       imageUrl: "/images/Products/Books/53-sarsv-bhag-ek.jpg",
       active: true,
     },
     {
       id: "54",
       sku: "BOOK-054",
       title: "Sarvasva Part-2",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 15000,
       imageUrl: "/images/Products/Books/54-sarsb-bhag-2.jpg",
       active: true,
     },
     {
       id: "55",
       sku: "BOOK-055",
       title: "Ek Or Muktidoot",
       category: "Book",
       description: "An introduction to Jain dharma and principles.",
       priceCents: 20000,
       imageUrl: "/images/Products/Books/55-ek-aur-muktidoot.jpg",
       active: true,
     },
    ],
  });

  console.log("✅ Products seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
